### ISSUE TITLE
Struct in a Struct breaks deserialization

### ISSUE THREAD

**Issue by Hannah-GBS** [Brendonovich/MacroGraph#468]
https://github.com/user-attachments/assets/f7d8c935-f0f6-4e8e-bdac-fa362b39f467

https://github.com/user-attachments/assets/ae24eb60-3818-4dc7-b988-eebca89e3994

```
index.ts:90:
 Uncaught (in promise) 
Error: Struct not found!
    at Option.expect (index.ts:90:9)
    at deserializeType (serialized.ts:82:36)
    at deserializeType (serialized.ts:79:17)
    at deserializeVariable (deserialize.ts:208:15)
    at deserialize.ts:231:46
    at Array.map (<anonymous>)
    at deserializeGraph (deserialize.ts:231:35)
    at deserialize.ts:103:26
    at Array.map (<anonymous>)
    at deserializeProject (deserialize.ts:102:6)

**Comment by Brendonovich** [comment]
c08ff5a38e9a
